name: Context Ex

on: [push]

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      
      - name: "My Step"
        run: echo "Hello $MY-ACTION"
        env:
          MY_ACTION: ${{ github.action }}