name: "workflow commands"

on: [push]
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
        - name: "group logging"
          run: |
            echo "::group:: My Group Message"
            echo "Msg1"
            echo "msg 2"
            echo "::end group::"
